const FETCH_ROCKETS = 'FETCH_ROCKETS';
const BOOK_ROCKET = 'BOOK_ROCKET';

const FETCH_MISSIONS = 'FETCH_MISSION';
const JOIN_MISSION = 'BOOK_ROCKET';

export { FETCH_ROCKETS, BOOK_ROCKET, FETCH_MISSIONS, JOIN_MISSION };
