const FETCH_ROCKETS = 'FETCH_ROCKETS';
const BOOK_ROCKET = 'BOOK_ROCKET';
const CANCEL_ROCKET = 'CANCEL_ROCKET';

const FETCH_MISSIONS = 'FETCH_MISSION';
const JOIN_MISSION = 'BOOK_ROCKET';

export {
  FETCH_ROCKETS, BOOK_ROCKET, CANCEL_ROCKET, FETCH_MISSIONS, JOIN_MISSION,
};
